language: php
php:
  - 7.4
  - hhvm
before_script:
 - composer self-update
 - composer install --prefer-source --no-interaction --dev
script: phpunit

deploy:
  provider: azure_web_apps
  username: AZURE_WA_PASSWORD
  password: AZURE_WA_USERNAME
  site: AZURE_WA_SITE